# Generated by Django 4.1 on 2022-08-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='starttime',
        ),
    ]
